name: Windows MinGW

on:
  push:
  pull_request:

jobs:
  build-and-test-windows-mingw:
    name: Build & Test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install meson build system
        run: python -m pip install meson

      - name: Upgrade MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: Configure build directory
        run: meson setup builddir

      - name: Compile project
        run: meson compile -C builddir

      - name: Run tests
        run: meson test -C builddir
